### ISSUE TITLE
 E5RT: Failed to PropagateInputTensorShapes ios18.mul error when use export example in the preview branch

### ISSUE THREAD

**Issue by frogcjn** [huggingface/swift-transformers#136]
I have used export example in the preview branch of [swift-transformer](https://github.com/huggingface/swift-transformers.
When I use the line to load model `let model = try MLModel(contentsOf: url, configuration: config)`,
it will throw error:
```
E5RT encountered an STL exception. msg = Failed to PropagateInputTensorShapes: std::invalid_argument during type inference for ios18.mul: Shapes are not compatible for broadcasting..
E5RT: Failed to PropagateInputTensorShapes: std::invalid_argument during type inference for ios18.mul: Shapes are not compatible for broadcasting. (11)
Failure translating MIL->EIR network: std::bad_cast
[Espresso::handle_ex_plan] exception=Espresso exception: "Network translation error": Unknown MIL->EIR network translation error: std::bad_cast status=14
Failed to build the model execution plan using a model architecture file '/.../hf-compiled-transformers/StatefulMistral7BInstructInt4.mlmodelc/model.mil' with error code: 14.
```

![Screenshot 2024-10-07 at 21 04 53](https://github.com/user-attachments/assets/9df4a5a3-ab38-43e2-b530-12dd9d7c7e90)

@junpeiz

**Comment by junpeiz** [comment]
Which MacOS are you using? Could you try it on the latest OS to see if the issue still persists?

**Comment by frogcjn** [comment]
Yes, it is the latest macOS, 15.1 Developer Beta 6 (24B5070a)

**Comment by junpeiz** [comment]
I verified that the model loading works well on my side by following steps:
- Download `StatefulMistral7BInstructInt4.mlpackage` from https://huggingface.co/apple/mistral-coreml
- Clone swift transformer repo `git clone -b preview https://github.com/huggingface/swift-transformers`
- Run by Python interface `python3 generate.py Examples/Mistral7B/StatefulMistral7BInstructInt4.mlpackage --prompt "Best recommendations for a place to visit in Paris in August 2024:"`

Did you download the CoreML model directly from https://huggingface.co/apple/mistral-coreml, or you do the conversion yourself by following steps in https://huggingface.co/blog/mistral-coreml? Could you share more detailed steps about how to reproduce the error? Thanks!

**Comment by frogcjn** [comment]
Yes. if I downloaded from Hugging Face, it could be work. But when I want to using the export.py example in hugging face, it will report the error.

My target is changing the input context limitation, that's why I want to use the export.py in preview branch of swift-transformer.

**Comment by junpeiz** [comment]
I would recommend to try it with the unmodified `export.py` with the latest `coremltools` (8.0) and `transformers`. 

If it doesn't work, it means a regression in coremltools/transformers stack.

If it works, but doesn't work after you modifying the context length, I can help to triage it to see if it's something that needs to be fixed in CoreML Framework.

**Comment by frogcjn** [comment]
Yes. I keep it no change, the last trail I do not change the context length, using original code, it still report the same error.

**Comment by junpeiz** [comment]
Hey @frogcjn , could you try to install the following versions of packages
```
coremltools==8.0
torch==2.4.0
transformers==4.45.2
```

And then run the following command
```
python export.py

python generate.py StatefulMistral7BInstructInt4.mlpackage --prompt "Best recommendations for a place to visit in Paris in August 2024:"
```

to see if it can successfully generate text on your side? I verified it on my side that it worked. Thanks!

**Comment by frogcjn** [comment]
Hi @junpeiz, I have tried.
```
python generate.py StatefulMistral7BInstructInt4.mlpackage --prompt "Best recommendations for a place to visit in Paris in August 2024:"
```
would work for `python generate.py ...`, it will generate:
```
python generate.py StatefulMistral7BInstructInt4.mlpackage --prompt "Best recommendations for a place to visit in Paris in August 2024:"
tokenizer_config.json: 100%|██████████████████| 141k/141k [00:00<00:00, 150MB/s]
tokenizer.model: 100%|███████████████████████| 587k/587k [00:00<00:00, 4.97MB/s]
tokenizer.json: 100%|██████████████████████| 1.96M/1.96M [00:00<00:00, 15.4MB/s]
special_tokens_map.json: 100%|█████████████████| 414/414 [00:00<00:00, 1.21MB/s]
loc("/Users/frogcjn/Library/Caches/python/com.apple.e5rt.e5bundlecache/24B5070a/0CACF4FCB21CDB69A735283553E73DAC2065DDACB23DA71D81D23146129F11CE/F3974406D092E8D35FD061F6D72241D5DFEFB2459BC9B91023817E404C4EE17A.bundle/H14G.bundle/main/main_mps_graph/main_mps_graph.mpsgraphpackage/model_0.mpsgraph":0:0): error: attempting to parse a byte at the end of the bytecode
<s> Best recommendations for a place to visit in Paris in August 2024:

1. Eiffel Tower: A must-visit attraction in Paris, the Eiffel Tower offers stunning views of the city. In August 2024, you can expect a lively atmosphere, especially during the evening when the tower sparkles.

2. Louvre Museum: Home to thousands of works of art, including the Mona Lisa and the Winged Victory of Samothrace, the Louvre is a cultural gem. It's advisable to book tickets in advance to avoid long queues.

3. Palace of Versailles: Located just outside of Paris
```
**but still not work for `let model = try MLModel(contentsOf: url, configuration: config)` in Swift Projects**

**Comment by frogcjn** [comment]
@junpeiz 
After successfully using the `export.py` converting model, I conducted a test. Here are the key findings:

When we set the `max_context_size`:
(1)from 2048 to 16384, it would fine both in Python `python generate.py` and Swift ` try MLModel(contentsOf: url, configuration: config)`
(2) greater or equal to 32768, it would report error both in Python and Swift:

```
python generate.py StatefulMistral7BInstructInt4-context32768.mlpackage --prompt "Best recommendations for a place to visit in Paris in August 2024:" 
Traceback (most recent call last):
  File "/Users/username/Documents/Projects/GitHub/swift-transformers/Examples/Mistral7B/generate.py", line 82, in <module>
    extend_text: str = generate(
  File "/Users/username/Documents/Projects/GitHub/swift-transformers/Examples/Mistral7B/generate.py", line 68, in generate
    for i, token in enumerate(get_next_token(model, prompt_tokens=prompt_tokens.astype(np.int32))):
  File "/Users/username/Documents/Projects/GitHub/swift-transformers/Examples/Mistral7B/generate.py", line 44, in get_next_token
    kv_cache_state = model.make_state()
  File "/Users/username/.pyenv/versions/3.10.13/lib/python3.10/site-packages/coremltools/models/model.py", line 808, in make_state
    return MLState(self.__proxy__.newState())
AttributeError: 'NoneType' object has no attribute 'newState'
```

```
E5RT encountered an STL exception. msg = Failed to PropagateInputTensorShapes: std::runtime_error during type inference for ios18.slice_by_index: zero shape error.
E5RT: Failed to PropagateInputTensorShapes: std::runtime_error during type inference for ios18.slice_by_index: zero shape error (11)
Failure translating MIL->EIR network: std::bad_cast
[Espresso::handle_ex_plan] exception=Espresso exception: "Network translation error": Unknown MIL->EIR network translation error: std::bad_cast status=14
Failed to build the model execution plan using a model architecture file '/Users/username/Library/Application Support/hf-compiled-transformers/StatefulMistral7BInstructInt4-context32768.mlmodelc/model.mil' with error code: 14.
No model could be loaded: Error Domain=com.apple.CoreML Code=0 "Failed to build the model execution plan using a model architecture file '/Users/username/Library/Application Support/hf-compiled-transformers/StatefulMistral7BInstructInt4-context32768.mlmodelc/model.mil' with error code: 14." UserInfo={NSLocalizedDescription=Failed to build the model execution plan using a model architecture file '/Users/username/Library/Application Support/hf-compiled-transformers/StatefulMistral7BInstructInt4-context32768.mlmodelc/model.mil' with error code: 14.}
```
